### ISSUE TITLE
out_autoencoder

### ISSUE THREAD

**Issue by choudharyharsh122** [gitmenonsandu/Image-denoising-using-convolutional-denoising-autoencoders#11]
what is this image array "out_autoencoder" which is first used in pynotebook standard-image-datasets, this variable isn't defined

**Comment by sandeepnmenon** [comment]
Have resolved that issue. It was a mistake of deleting a cell. Sorry for the confusion.
Correction made in commit 7572b180d59486d03d46c0377a7b91528d377b8d
