### ISSUE TITLE
gaussian_noise

### ISSUE THREAD

**Issue by golapraj** [gitmenonsandu/Image-denoising-using-convolutional-denoising-autoencoders#12]
NameError                                 Traceback (most recent call last)
<ipython-input-169-449986d27f0a> in <module>()
      6 noisy_set = images
      7 ground_truth,noisy_images = pair_shuffle(images,noisy_set)
----> 8 add_noise(images)

<ipython-input-161-ed5fa333ce6d> in add_noise(images)
      4     #x_test = np.reshape(x_test, (len(x_test), 64*64))  # adapt this if using `channels_first` image data format
      5     batch = images.shape[0]//4;
----> 6     noise1 = gaussian_noise(images[0:batch],0,25,0.1)
      7     noise2 = gaussian_noise(images[batch:2*batch],0,30,0.5)
      8     noise3 = gaussian_noise(images[2*batch:3*batch],0,35,0.21)

NameError: name 'gaussian_noise' is not defined

**Comment by sandeepnmenon** [comment]
Thank you for bringing it into my notice.
Solved in commit ddbfcf84dbd8b4cf4447914f3bf31c6d251b0fc9
